don_index:
    path:     /
    defaults: { _controller: "EntraideBundle:don:index" }
    methods:  GET

don_show:
    path:     /{id}/show
    defaults: { _controller: "EntraideBundle:don:show" }
    methods:  GET

don_new:
    path:     /{id}/new
    defaults: { _controller: "EntraideBundle:don:new" }
    methods:  [GET, POST]

don_edit:
    path:     /{id}/edit
    defaults: { _controller: "EntraideBundle:don:edit" }
    methods:  [GET, POST]

don_delete:
    path:     /{id}/delete
    defaults: { _controller: "EntraideBundle:don:delete" }
    methods:  DELETE
