entraide_index:
    path:     /
    defaults: { _controller: "EntraideBundle:entraide:index" }
    methods:  GET

entraide_show:
    path:     /{id}/show
    defaults: { _controller: "EntraideBundle:entraide:show" }
    methods:  GET

entraide_new:
    path:     /new
    defaults: { _controller: "EntraideBundle:entraide:new" }
    methods:  [GET, POST]

entraide_edit:
    path:     /{id}/edit
    defaults: { _controller: "EntraideBundle:entraide:edit" }
    methods:  [GET, POST]

entraide_delete:
    path:     /{id}/delete
    defaults: { _controller: "EntraideBundle:entraide:delete" }
    methods:  DELETE
