g_publication:
    resource: "@GPublicationBundle/Resources/config/routing.yml"
    prefix:   /

events:
    resource: "@EventsBundle/Resources/config/routing.yml"
    prefix:   /

amicale:
    resource: "@AmicaleBundle/Resources/config/routing.yml"
    prefix:   /

entraide:
    resource: "@EntraideBundle/Resources/config/routing.yml"
    prefix:   /

formation:
    resource: "@FormationBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

discutea_forum:
    resource: "@DForumBundle/Resources/config/routing.yml"
    prefix:   /


    


