<?php

namespace EventsBundle\Repository;

/**
 * agendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class agendaRepository extends \Doctrine\ORM\EntityRepository
{
}
