<?php

namespace AmicaleBundle\Repository;

/**
 * AmicaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AmicaleRepository extends \Doctrine\ORM\EntityRepository
{

    function viewQB($id){
        $em=$this->getEntityManager();

        $query = $em->createQuery('SELECT a.nomAmicale,a.typeAmicale,a.montantAmicale,a.descriptionAmicale FROM AmicaleBundle:Amicale a WHERE a.user=?1');

        $users = $query->setParameter(1,$id)->getResult();

        return $users;
    }



    function view3QB($id){
        $em=$this->getEntityManager();

        $query = $em->createQuery('SELECT a.nomAmicale,a.typeAmicale,a.montantAmicale,a.descriptionAmicale FROM AmicaleBundle:Amicale a WHERE a.visi=?1');

        $users = $query->setParameter(1,$id)->getResult();

        return $users;
    }


}
